services:
    form_select.twig_extension:
        class: GlauberKyves\ZendFormTwigBundle\Twig\FormSelectExtension
        arguments:  ["@service_container"]
        tags:
            - { name: twig.extension }